1번 프로젝트 완료!
gitproject-team1/miniProject pull request #14
Opened 2022-11-21 16:34 UTC by hyorimcho

# 📌 Color Flipper 만들어보기

JS의 기초부터 심화까지 키우기위한 미니프로젝트 - 1
1조 미니프로젝트 뿌수기 🦾

## 데모주소

데모는 [여기서](https://colorflipper-hyocho.netlify.app/) 보실 수 있습니다.

## 기간

- 2022/11/21

## 사용 스택

<img src="https://img.shields.io/badge/html5-E34F26?style=for-the-badge&logo=html5&logoColor=white">
<img src="https://img.shields.io/badge/css-1572B6?style=for-the-badge&logo=css3&logoColor=white">
<img src="https://img.shields.io/badge/javascript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black">

## 사용 개념

- arrays
- document.getElementById()
- document.querySelector()
- addEventListener()
- document.body.style.backgroundColor
- Math.floor()
- Math.random()
- array.length

## 구현사항

- [x] 버튼이 hover 되었을때 디자인을 추가해보세요
- [x] Hex모드와 심플모드간의 전환이 가능하게 해보세요(심플모드는 빨주노초파남보 중에 랜덤으로 합니다)
- [x] 색상변경에 순서가없이 랜덤하게 되도록 해보세요
- [ ] SPA로 구현해보세요
- [x] 알아서 멋지게 완성시켜보세요!

## 주의사항

- 유튜브 튜토리얼은 보지 않는걸 추천합니다. 결과물만 보고 동작을 유추해봅시다
- 매번 배포는 힘드므로 번들러 사용없이, SCSS가 아닌 CSS로만 구성해봅시다(다른분들이 다운받아서 라이브서버로 열수있게)
- README.md를 꼭 작성해봅시다
- Git Flow 전략을 적용해봅시다
- Commit message는 최우영 강사님의 것을 따릅니다
- 별도의 폴더를 만들어서 pull request를 보냅니다
- 서로의 것을 열심히 코드리뷰하고 칭찬합시다!

2022-11-21 16:55 UTC, ghgt1 requested changes
hex.js를 빼먹은듯해요!!!! hex모드가 동작을안하네요 
다시 추가해서 부탁드립니다!

2022-11-21 17:11 UTC, ghgt1 requested changes
main.js가 덮어씌워지는 문제가 있는것 같아요 ㅜㅜ 
link를 분리해줘야할거같아요!

2022-11-21 17:45 UTC, ghgt1 reviewed
고생하셨씁니당!

마찬가지로
- 데모 사이트의 첫화면은 hex모드와 simple모드가 섞여서 나오는것을 확인할수있음(원리는 모르겠네요). 이것도 구현할수있으면 좋을듯
- 복잡한 로직이 아니니까 SPA가 필요없기도 하지만, 우선 거의 동일한 두개의 html을 다 로드한다는거 자체가 아쉬운 상황. 다음엔 연습겸 하나로 줄여보아요!!

2022-11-21 17:45 UTC, ghgt1 commented on ChoHyoRim/ColorFlipper/hex.js
> +const hexColors = [
다음엔 하드코딩이 아닌 진짜 난수 생성을 해보아요!!

2022-11-21 17:45 UTC, ghgt1 commented on ChoHyoRim/ColorFlipper/hex.js
> +}
함수 선언식의 호이스팅을 실제로 잘사용하셨네요!

2022-11-21 17:45 UTC, ghgt1 commented on ChoHyoRim/ColorFlipper/main.js
> +}
이함수 잘하면 모듈화로 재사용할수있을지도....(안될수도)?

2022-11-21 17:45 UTC, ghgt1 commented on ChoHyoRim/ColorFlipper/style.css
> +  gap: 20px;
gap속성 자주 안썼었는데 대단합니다!

2022-11-22 02:19 UTC, hyorimcho commented on ChoHyoRim/ColorFlipper/main.js
> +}
오, 그러네요? js, html 하나씩으로 만들 때에 이 부분도 함께 신경써서 보도록 하겠습니다! 감사해요👍

2022-11-22 02:20 UTC, hyorimcho commented on ChoHyoRim/ColorFlipper/style.css
> +  gap: 20px;
쓰다보니 gap 이 참 쉽게 느껴지더라고요..?😊 추천드립니다!

2022-11-22 03:18 UTC, 1myeji reviewed
깔끔한 css js 잘 봤습니다!! 코드리뷰 좋은거였다..! 코드리뷰 하면서 제 코드를 어떻게 좋은 방향으로 수정할 수 있을지 배우는게 많을 것 같아요ㅎㅎ

2022-11-22 03:18 UTC, 1myeji commented on ChoHyoRim/ColorFlipper/main.js
> +  document.body.style.backgroundColor = colors[randomNumber];
저는 queryselector로 body를 찾았었는데 이렇게 하면 됐었네요!

2022-11-22 03:18 UTC, 1myeji commented on ChoHyoRim/ColorFlipper/main.js
> +function getRandomNumber() {
이 코드 함수로 만들어주셨네요..! good👍

2022-11-22 03:20 UTC, 1myeji commented on ChoHyoRim/ColorFlipper/hex.js
> +const hexColors = [
도전 도전!

2022-11-22 03:20 UTC, 1myeji commented on ChoHyoRim/ColorFlipper/hex.js
> +const hexColors = [
도전 도전!

2022-11-23 08:22 UTC, merged